### PR TITLE
Dashboard + Client listing + Update Select2

### PR DESCRIPTION
**Pull request by dansleboby**
image
image

### CODE REVIEW

**Comment by dampelz** [comment]
it,s strange but select2 style is not working, and buttons is not working
clients

**Comment by dansleboby** [comment]
I found the issue, but for me "locked" was working, for the button it a class issue I will fix that shortely

**Comment by dampelz** [comment]
can you check select2 again, maybe you can fix it

**Comment by dampelz** [comment]
yes, select is working, but how to disable background gray style for arrow button.
I'm using Firefox,

**Comment by schnere** [comment]
Thank you very much for your contribution.
For the existing templates I've updated the icon classes, but as you have renamed the classes more themplates from the parent theme will have to get added to fix the classes.

**Pull request merged**
